#!/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)
# run like dis:
# Rscript --vanilla full_chromome_plot.R $sampleID
# or via loop of course
#cat SNCA_samples_moving_forward.txt | while read line
#do 
#	Rscript --vanilla full_chromome_plot.R $line
#done
#
# check if sample name works
SAMPLENAME = args[1]
print(args[1])
print(SAMPLENAME)
### prep in terminal
# starting prep for plot with all chromosomes....
#for chnum in {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22};
#  do
#	cut -d " " -f $LINE_NUMBERS_OF_INTEREST ../BAF/ukb_baf_chr"$chnum"_v2.txt > FULL_CHR"$chnum"_ukb_baf_v2_SOI.txt
#	cut -d " " -f $LINE_NUMBERS_OF_INTEREST ../L2R/ukb_l2r_chr"$chnum"_v2.txt > FULL_CHR"$chnum"_ukb_l2r_v2_SOI.txt
#done
# basically looks like this:
# cut -d " " -f 32868,71249,96701,283140,350996,353013 BAF/ukb_baf_chr"$chnum"_v2.txt > FULL_CHR"$chnum"_ukb_baf_v2_SOI_EXTRA.txt
# module load R
# R
require(data.table)
###########
# BAF
###########
# read in and process data 
for(i in 1:22) {
BAF <- fread(paste("FULL_CHR",(i),"_ukb_baf_v2_SOI.txt",sep=""),header=F)
BIM <- fread(paste("../BIM/ukb_snp_chr",(i),"_v2.bim",sep=""),header=F)
BIM$V1 <- NULL
BIM$V2 <- NULL
BIM$V3 <- NULL
BIM$V5 <- NULL
BIM$V6 <- NULL
PLOT_BAF_large <- cbind(BIM,BAF)
colnames(PLOT_BAF_large)<- c("BP",$SAMPLENAMES_OF_INTEREST)
assign(paste("chr",(i),"_data",sep=""), PLOT_BAF_large)
}
# now plot
options(scipen=20)
pdf(paste(SAMPLENAME,"_full_genome_BAF.pdf",sep=""),width=12)
par(mar=c(3, 2, 3, 1))
par(mfrow=c(3,4))
plot(chr1_data$BP,chr1_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 1 basepair",main="Full chromosome 1 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr2_data$BP,chr2_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 2 basepair",main="Full chromosome 2 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr3_data$BP,chr3_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 3 basepair",main="Full chromosome 3 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr4_data$BP,chr4_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 4 basepair",main="Full chromosome 4 BAF")
rect(xleft=90645250,xright = 90759447,ybottom=par("usr")[3], ytop=par("usr")[4], density=10, col = "red")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr5_data$BP,chr5_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 5 basepair",main="Full chromosome 5 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr6_data$BP,chr6_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 6 basepair",main="Full chromosome 6 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr7_data$BP,chr7_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 7 basepair",main="Full chromosome 7 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr8_data$BP,chr8_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 8 basepair",main="Full chromosome 8 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr9_data$BP,chr9_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 9 basepair",main="Full chromosome 9 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr10_data$BP,chr10_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 10 basepair",main="Full chromosome 10 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr11_data$BP,chr11_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 11 basepair",main="Full chromosome 11 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr12_data$BP,chr12_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 12 basepair",main="Full chromosome 12 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr13_data$BP,chr13_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 13 basepair",main="Full chromosome 13 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr14_data$BP,chr14_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 14 basepair",main="Full chromosome 14 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr15_data$BP,chr15_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 15 basepair",main="Full chromosome 15 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr16_data$BP,chr16_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 16 basepair",main="Full chromosome 16 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr17_data$BP,chr17_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 17 basepair",main="Full chromosome 17 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr18_data$BP,chr18_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 18 basepair",main="Full chromosome 18 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr19_data$BP,chr19_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 19 basepair",main="Full chromosome 19 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr20_data$BP,chr20_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 20 basepair",main="Full chromosome 20 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr21_data$BP,chr21_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 21 basepair",main="Full chromosome 21 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
plot(chr22_data$BP,chr22_data[[SAMPLENAME]],pch=20,ylab="B allele frequency",xlab="CHR 22 basepair",main="Full chromosome 22 BAF")
abline(h=0.66, col="blue")
abline(h=0.33, col="blue")
abline(h=0.5, col="blue", lwd = 3)
grid()
dev.off()
###########
# L2R
###########
# read in and process data 
for(i in 1:22) {
L2R <- fread(paste("FULL_CHR",(i),"_ukb_l2r_v2_SOI.txt",sep=""),header=F)
BIM <- fread(paste("../BIM/ukb_snp_chr",(i),"_v2.bim",sep=""),header=F)
BIM$V1 <- NULL
BIM$V2 <- NULL
BIM$V3 <- NULL
BIM$V5 <- NULL
BIM$V6 <- NULL
PLOT_L2R_large <- cbind(BIM,L2R)
colnames(PLOT_L2R_large)<- c("BP",$SAMPLENAMES_OF_INTEREST)
assign(paste("chr",(i),"_data",sep=""), PLOT_L2R_large)
}
# now plot
options(scipen=20)
pdf(paste(SAMPLENAME,"_full_genome_L2R.pdf",sep=""),height=20,width=12)
par(mar=c(3, 2, 3, 1))
par(mfrow=c(3,4))
plot(chr1_data$BP,chr1_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 1 basepair",main="Full chromosome 1 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr1_data$BP,chr1_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr2_data$BP,chr2_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 2 basepair",main="Full chromosome 2 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr2_data$BP,chr2_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr3_data$BP,chr3_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 3 basepair",main="Full chromosome 3 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr3_data$BP,chr3_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr4_data$BP,chr4_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 4 basepair",main="Full chromosome 4 L2R")
rect(xleft=90645250,xright = 90759447,ybottom=par("usr")[3], ytop=par("usr")[4], density=10, col = "red")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr4_data$BP,chr4_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr5_data$BP,chr5_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 5 basepair",main="Full chromosome 5 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr5_data$BP,chr5_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr6_data$BP,chr6_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 6 basepair",main="Full chromosome 6 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr5_data$BP,chr5_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr7_data$BP,chr7_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 7 basepair",main="Full chromosome 7 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr5_data$BP,chr5_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr8_data$BP,chr8_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 8 basepair",main="Full chromosome 8 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr6_data$BP,chr6_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr9_data$BP,chr9_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 9 basepair",main="Full chromosome 9 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr1_data$BP,chr1_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr10_data$BP,chr10_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 10 basepair",main="Full chromosome 10 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr1_data$BP,chr1_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr11_data$BP,chr11_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 11 basepair",main="Full chromosome 11 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr1_data$BP,chr1_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr12_data$BP,chr12_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 12 basepair",main="Full chromosome 12 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr1_data$BP,chr1_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr13_data$BP,chr13_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 13 basepair",main="Full chromosome 13 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr1_data$BP,chr1_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr14_data$BP,chr14_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 14 basepair",main="Full chromosome 14 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr1_data$BP,chr1_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr15_data$BP,chr15_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 15 basepair",main="Full chromosome 15 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr1_data$BP,chr1_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr16_data$BP,chr16_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 16 basepair",main="Full chromosome 16 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr1_data$BP,chr1_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr17_data$BP,chr17_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 17 basepair",main="Full chromosome 17 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr1_data$BP,chr1_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr18_data$BP,chr18_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 18 basepair",main="Full chromosome 18 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr1_data$BP,chr1_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr19_data$BP,chr19_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 19 basepair",main="Full chromosome 19 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr1_data$BP,chr1_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr20_data$BP,chr20_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 20 basepair",main="Full chromosome 20 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr2_data$BP,chr2_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr21_data$BP,chr21_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 21 basepair",main="Full chromosome 21 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr2_data$BP,chr2_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
plot(chr22_data$BP,chr22_data[[SAMPLENAME]],pch=20,ylab="L2R ratio",xlab="CHR 22 basepair",main="Full chromosome 22 L2R")
abline(h=0, col="blue", lwd = 3)
lines(lowess(chr2_data$BP,chr2_data[[SAMPLENAME]],f = 0.0001), col="red", lwd = 3)
grid()
dev.off()
# ALL DONE
